# Generated by Django 3.0.4 on 2020-04-17 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotePad',
            new_name='Note',
        ),
    ]
